### PR TITLE
Complete Front-End Dev Exercise for applicants

### PR DESCRIPTION
**Pull request by isaiahgrey93**

### CODE REVIEW

**Comment by isaiahgrey93** [comment]
Hello devlopwithapurpose,
I am cleaning up my github, and was wondering if you would delete my closed pull request.
Username: isaiahgrey93.
If you can I would appreciate it. Thanks.

**Comment by jmmcduffie** [comment]
The pull request is closed. Are you talking about deleting the fork?

**Comment by isaiahgrey93** [comment]
Yes, sorry I meant to specify that, is that something you are able to do
for me? I appreciate your time.

On Mon, Jan 26, 2015 at 5:40 AM, Jeremy McDuffie <notifications@github.com>
wrote:

> The pull request is closed. Are you talking about deleting the fork?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/developwithpurpose/front-end-developer-exercise/pull/21#issuecomment-71461711>
> .
>



-- 
~*Isaiah Grey*

**Comment by jmmcduffie** [comment]
No, your fork is under your control. Also, I don't see your name in [the list of forks](https://github.com/developwithpurpose/front-end-developer-exercise/network/members) anymore and it says `unknown repository` on this PR, so perhaps you've already deleted it?

**Pull request closed without merging**
